### ISSUE TITLE
Kafka Version

### ISSUE THREAD

**Issue by adhip94** [hayrullahcansu/log4net-kafka-appender#3]
I have a .Net Core 3.0 application and .Net Standard 2.1 Class Library that already use Kafka for message queuing. I am looking to integrate Kafka with Log4net, I have tried your library and I am getting this error.

`Could not load type 'Confluent.Kafka.Producer' from assembly 'Confluent.Kafka, Version=1.3.0.0, Culture=neutral, PublicKeyToken=12c514ca49093d1e'.`

This is probably because you are using the old version of Kafka, whereas I am using the latest version (1.3.0).

Is it possible for you to do the required changes?

**Comment by hayrullahcansu** [comment]
Hello,
Actually log4net is deprecated project for .netcore2+. So you should use nlog as logger.
https://github.com/hayrullahcansu/nlog-kafka-target
